# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: umccr
builds:
- env:
  - CGO_ENABLED=0
  goarch:
    - amd64
    - arm64
  goos:
    - linux
    - darwin
    - windows
  ignore:
      - goos: darwin
        goarch: 386
      - goos: linux
        goarch: 386
archives:
  - replacements:
      darwin: OSX
      linux: Linux
      windows: Windows
      amd64: x86_64
    format: binary
    name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}-{{.Arch}}"
    files:
      - 'none*'

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
