# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: umccr
builds:
- env:
  - CGO_ENABLED=0
  goarch:
    - amd64
    - arm64
  goos:
    - linux
    - darwin
    - windows
  ignore:
      - goos: darwin
        goarch: 386
      - goos: linux
        goarch: 386
archives:
  - replacements:
      darwin: OSX
      linux: Linux
      windows: Windows
      amd64: x86_64
    format: binary
    name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}-{{.Arch}}"
    files:
      - 'none*'

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

brews:
  name: umccr
  github:
    owner: umccr
    name: cli
  url_template: "http://github.com/umccr/releases/{{ .Tag }}/{{ .ArtifactName }}"
  commit_author:
    name: umccr_cli_goreleaser_bot
    email: goreleaser@umccr.org
  folder: Formula
  homepage: "https://github.com/umccr/cli"
  description: "UMCCR organizational command line interface."

  # Setting this will prevent goreleaser to actually try to commit the updated
  # formula - instead, the formula file will be stored on the dist folder only,
  # leaving the responsibility of publishing it to the user.
  # If set to auto, the release will not be uploaded to the homebrew tap
  # in case there is an indicator for prerelease in the tag e.g. v1.0.0-rc1
  # Default is false.
  skip_upload: true

  # Custom install script for brew.
  # Default is 'bin.install "program"'.
  install: |
    bin.install {{ .ArtifactName }}
