language: go
sudo: false

go:
    - 1.x
install:
  - go get github.com/umccr/cli
matrix:
  include:
    - go: 1.x
  fast_finish: true

deploy:
  provider: script 
  skip_cleanup: true
  script: curl -sL http://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux

notifications:
  email: false
