language: go
sudo: false

go:
    - 1.13.4
matrix:
  include:
    - go: 1.13.4
  fast_finish: true

before_deploy:
  - go get github.com/inconshreveable/mousetrap # windows support

deploy:
  provider: script 
  skip_cleanup: true
  script: curl -sL http://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux

notifications:
  email: false
